# Global Settings
# When USE_CHEZMOI is true, `chezmoi add` will run against each changes
USE_CHEZMOI=true
# When DELETE_MISSING_SKILLS is true, target skill folders missing from templates will be removed.
DELETE_MISSING_SKILLS=false

# Agent Configuration Map
# Format: Agent Name|Target AGENTS.md Path|Target Skills Directory Path
# Lines starting with # are ignored.
# Example:
# Gemini|~/.gemini/AGENTS.md|~/.gemini/skills

amp|~/.config/AGENTS.md|
codex|~/.codex/AGENTS.md|~/.codex/skills/
droid|~/.factory/AGENTS.md|~/.factory/skills/
gemini|~/.gemini/GEMINI.md|~/.gemini/skills/
# global|~/.agents/AGENTS.md|~/.agents/skills/
opencode|~/.config/opencode/AGENTS.md|~/.config/opencode/skill/
pi|~/.pi/agent/AGENTS.md|~/.pi/agent/skills/
qwen|~/.qwen/QWEN.md|~/.qwen/skills/
